# Generated by Django 4.2.30 on 2026-06-13 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildSettings',
            fields=[
                ('guild_id', models.TextField(primary_key=True, serialize=False)),
                ('prefix', models.TextField(default='!')),
                ('welcome_enabled', models.IntegerField(default=0)),
                ('welcome_channel_id', models.TextField(blank=True, null=True)),
                ('welcome_message', models.TextField(default='Willkommen {user} auf dem Server {server}!')),
                ('welcome_dm_enabled', models.IntegerField(default=0)),
                ('welcome_dm_message', models.TextField(default='Hallo {user}, willkommen auf {server}!')),
                ('goodbye_enabled', models.IntegerField(default=0)),
                ('goodbye_channel_id', models.TextField(blank=True, null=True)),
                ('goodbye_message', models.TextField(default='{user} hat den Server verlassen.')),
                ('ticket_enabled', models.IntegerField(default=0)),
                ('ticket_category_id', models.TextField(blank=True, null=True)),
                ('ticket_staff_role_id', models.TextField(blank=True, null=True)),
                ('ticket_welcome_message', models.TextField(default='Ein Teammitglied wird sich bald um dein Anliegen kümmern.')),
                ('news_enabled', models.IntegerField(default=0)),
                ('news_channel_id', models.TextField(blank=True, null=True)),
                ('news_rss_url', models.TextField(blank=True, null=True)),
                ('video_enabled', models.IntegerField(default=0)),
                ('video_channel_id', models.TextField(blank=True, null=True)),
                ('video_youtube_channel', models.TextField(blank=True, null=True)),
                ('moderation_enabled', models.IntegerField(default=0)),
                ('moderation_log_channel_id', models.TextField(blank=True, null=True)),
                ('autorole_enabled', models.IntegerField(default=0)),
                ('autorole_role_id', models.TextField(blank=True, null=True)),
                ('logging_enabled', models.IntegerField(default=0)),
                ('logging_channel_id', models.TextField(blank=True, null=True)),
                ('automod_enabled', models.IntegerField(default=0)),
                ('automod_badwords', models.TextField(blank=True, null=True)),
                ('automod_block_links', models.IntegerField(default=0)),
                ('automod_block_invites', models.IntegerField(default=0)),
                ('levels_enabled', models.IntegerField(default=0)),
                ('levels_channel_id', models.TextField(blank=True, null=True)),
                ('levels_message', models.TextField(default='Glückwunsch {user}, du hast Level {level} erreicht!')),
                ('reactionroles_enabled', models.IntegerField(default=0)),
                ('giveaway_enabled', models.IntegerField(default=0)),
                ('suggestions_enabled', models.IntegerField(default=0)),
                ('suggestions_channel_id', models.TextField(blank=True, null=True)),
                ('tempvoice_enabled', models.IntegerField(default=0)),
                ('tempvoice_category_id', models.TextField(blank=True, null=True)),
                ('tempvoice_channel_id', models.TextField(blank=True, null=True)),
                ('serverstats_enabled', models.IntegerField(default=0)),
                ('serverstats_category_id', models.TextField(blank=True, null=True)),
                ('customcommands_enabled', models.IntegerField(default=0)),
                ('economy_enabled', models.IntegerField(default=0)),
                ('birthday_enabled', models.IntegerField(default=0)),
                ('birthday_channel_id', models.TextField(blank=True, null=True)),
                ('birthday_role_id', models.TextField(blank=True, null=True)),
                ('poll_enabled', models.IntegerField(default=0)),
                ('counting_enabled', models.IntegerField(default=0)),
                ('tags_enabled', models.IntegerField(default=0)),
                ('verification_enabled', models.IntegerField(default=0)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('updated_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guild_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('guild_id', models.TextField()),
                ('user_id', models.TextField()),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('last_message_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'levels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('guild_id', models.TextField()),
                ('channel_id', models.TextField(blank=True, null=True)),
                ('user_id', models.TextField()),
                ('subject', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='open')),
                ('created_at', models.TextField(blank=True, null=True)),
                ('closed_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warn',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('guild_id', models.TextField()),
                ('user_id', models.TextField()),
                ('moderator_id', models.TextField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('warned_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'warns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('discord_access_token', models.TextField(blank=True, null=True)),
                ('discord_refresh_token', models.TextField(blank=True, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('last_guild_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
